services:
  api:
      image: objectobjectlady/fastapi
      depends_on:
          - postgres
      ports:
          - 80:8000
      # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      env_file:
          - ./.env

  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}
    
    volumes:
        - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: 